version: '{build}'

platform:
  - x64

services:
  - mssql2017

shallow_clone: true

environment:
  matrix:
    - { NODE_VERSION: 10, DIALECT: mssql }

install:
  - ps: Install-Product node $env:NODE_VERSION x64
  # - ps: |
  #     $pkg = ConvertFrom-Json (Get-Content -Raw package.json)
  #     $pkg.dependencies.PSObject.Properties.Remove('sqlite3')
  #     ConvertTo-Json $pkg | Out-File package.json -Encoding UTF8
  - npm i --production
  - npm i tedious@^6

build: off

before_test:
  - ps: . .\setup\appveyor-setup.ps1

test_script:
  - 'npm run ci'
